name: Image Build and Push

env:
  IMAGE_NAME: ghcr.io/justereseau/omni_etcd_backup

on:
  push:
    branches-ignore: ["main"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Try to build the image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64,linux/arm/v7
          push: false
          tags: "${{ env.IMAGE_NAME }}:dev"

      - name: List the images
        run: docker images

      - name: Try to run the image
        run: docker run --rm "${{ env.IMAGE_NAME }}:dev"
